server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Кеширование статических ресурсов для ускорения отдачи страниц
    location ~* \.(?:ico|css|js|gif|jpe?g|png|theme|svg|woff2?|eot|ttf|otf|webp)$ {
        expires 30d;
        add_header Cache-Control "public, no-transform";
    }
}
